version: "3.7"
services:
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: 'go'
    environment:
      - PORT=80
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - MYSQL_DATABASE=${DATABASE}
    networks:
      - home
    depends_on:
      - "db"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: 'nginx'
    networks:
      - home
    ports:
      - 8080:80
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: 'front'
    networks:
      - home
  db:
    image: mysql:8.0
    container_name: 'db'
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - MYSQL_DATABASE=${DATABASE}
      - TZ=Asia/Tokyo
    env_file:
      - ./db/db.env
    networks:
      - home
    volumes:
      - ./db/cnf:/etc/mysql/conf.d
      - ./db/data:/docker-entrypoint-initdb.d
networks:
  home:
    driver: bridge
